import { useEffect, useRef, useState } from "react";
import { Search, X } from "lucide-react";
import { searchRoomCandidates } from "../api/roomApi.js";

export default function AddMembersModal({ existingIds, error = "", onAdd, onClose }) {
  const [query, setQuery] = useState(""); const [results, setResults] = useState([]); const [selected, setSelected] = useState(new Set()); const [saving, setSaving] = useState(false); const requestRef = useRef(null);
  useEffect(() => { requestRef.current?.abort(); if (!query.trim()) return undefined; const controller = new AbortController(); requestRef.current = controller; const timer = setTimeout(() => searchRoomCandidates(query.trim(), { signal: controller.signal }).then((users) => setResults(users.filter((user) => !existingIds.has(String(user.userId))))).catch(() => {}), 250); return () => { clearTimeout(timer); controller.abort(); }; }, [existingIds, query]);
  async function submit() { if (!selected.size || saving) return; setSaving(true); try { const result = await onAdd([...selected]); if (result?.ok) onClose(); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/35 p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div role="dialog" aria-modal="true" aria-label="Add room members" className="w-full max-w-md rounded-[18px] bg-white p-5 shadow-xl dark:bg-[#20242B]"><div className="flex items-center justify-between"><h2 className="text-[18px] font-semibold">Add members</h2><button type="button" onClick={onClose}><X size={19} /></button></div><div className="relative mt-4"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#999EA6]" size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search users" className="h-11 w-full rounded-xl border border-[#E5E7E4] bg-transparent pl-9 pr-3 text-[13px] outline-none focus:border-[#3B82F6]/50 dark:border-white/[0.08]" /></div>{error && <p className="mt-3 rounded-xl bg-[#FBF1F1] p-3 text-[12px] text-[#A55353] dark:bg-[#3A2528] dark:text-[#E3A1A1]" role="alert">{error}</p>}<div className="mt-3 max-h-64 overflow-y-auto">{results.map((user) => <label key={user.userId} className="flex items-center gap-3 rounded-lg px-2 py-2 hover:bg-black/[0.03] dark:hover:bg-white/[0.05]"><input type="checkbox" checked={selected.has(String(user.userId))} onChange={() => setSelected((current) => { const next = new Set(current); const id = String(user.userId); if (next.has(id)) next.delete(id); else next.add(id); return next; })} /><span className="text-[13px]">{user.displayName || user.username}</span></label>)}</div><button type="button" disabled={!selected.size || saving} onClick={submit} className="mt-4 h-11 w-full rounded-xl bg-[#3B82F6] text-[13px] font-semibold text-white disabled:opacity-50">{saving ? "Adding..." : "Add selected"}</button></div></div>;
}
