import { useMemo, useState } from "react";
import { ArrowLeft, Camera, Plus, Save, X } from "lucide-react";
import Avatar from "../../../components/Chat/Avatar.jsx";
import { resolveUploadedFileUrl } from "../../../api/fileApi.js";
import { getRoomPermissions } from "../utils/roomPermissions.js";
import AddMembersModal from "./AddMembersModal.jsx";
import RoomMediaGrid from "./RoomMediaGrid.jsx";
import RoomMembersList from "./RoomMembersList.jsx";
import RoomSettingsSection from "./RoomSettingsSection.jsx";

export default function RoomDetailsPanel({ controller, currentUserId, onlineUserKeys, muted, pinned, onMessageMember, onOpenProfile, onMute, onPin, onClear, onExited }) {
  const { open, closeDetails, details, media, mediaHasMore, loading, error, save, saveAvatar, addMembers, removeMember, setRole, loadMoreMedia, exit } = controller;
  const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(null); const [showAdd, setShowAdd] = useState(false); const [confirmExit, setConfirmExit] = useState(false); const [actionError, setActionError] = useState("");
  const memberIds = useMemo(() => new Set(details?.members?.map((member) => String(member.userId)) ?? []), [details?.members]);
  if (!open) return null;
  const permissions = getRoomPermissions(details, currentUserId);
  async function run(action) { setActionError(""); try { await action(); } catch (requestError) { setActionError(requestError.response?.data?.error ?? requestError.message); } }
  async function submitEdit() { await run(async () => { await save(draft); setEditing(false); }); }
  async function handleExit() { await run(async () => { const deletedConversations = await exit(); onExited(deletedConversations); }); }
  return <aside className="fixed inset-0 z-[60] flex min-h-0 flex-col bg-[#F7F7F5] text-[#202226] dark:bg-[#111315] dark:text-[#F4F5F6] md:left-auto md:w-[390px] md:border-l md:border-[#E6E8E5] md:shadow-[-8px_0_24px_rgba(20,22,26,0.06)] dark:md:border-white/[0.07]">
    <header className="flex h-[72px] shrink-0 items-center gap-2 border-b border-[#E6E8E5] bg-white px-4 dark:border-white/[0.07] dark:bg-[#181A1F]"><button type="button" onClick={closeDetails} aria-label="Back to conversation" className="flex h-10 w-10 items-center justify-center rounded-xl hover:bg-black/[0.04] dark:hover:bg-white/[0.06] md:hidden"><ArrowLeft size={20} /></button><h2 className="text-[18px] font-semibold">Room Details</h2><button type="button" onClick={closeDetails} aria-label="Close room details" className="ml-auto hidden h-10 w-10 items-center justify-center rounded-xl hover:bg-black/[0.04] dark:hover:bg-white/[0.06] md:flex"><X size={19} /></button></header>
    <div className="min-h-0 flex-1 overflow-y-auto px-5 py-6">{loading && <p className="py-10 text-center text-[13px] text-[#8C9198]">Loading room details...</p>}{error && <p className="rounded-xl bg-[#FBF1F1] p-3 text-[12px] text-[#A55353] dark:bg-[#3A2528] dark:text-[#E3A1A1]">{error}</p>}{details && <>
      <section className="text-center"><div className="relative mx-auto w-fit"><Avatar size="lg" imageSrc={resolveUploadedFileUrl(details.avatar)} initials={details.name.slice(0, 2).toUpperCase()} group tone="bg-[#E4ECF7] text-[#355A7A] dark:bg-[#2B3848] dark:text-[#C5DBEE]" />{permissions.canManageRoom && <label className="absolute -bottom-1 -right-2 flex h-7 w-7 cursor-pointer items-center justify-center rounded-full bg-[#3B82F6] text-white"><Camera size={14} /><input type="file" accept="image/*" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) run(() => saveAvatar(file)); }} /></label>}</div>{editing ? <div className="mt-4 space-y-2"><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} className="h-10 w-full rounded-xl border border-[#E5E7E4] bg-white px-3 text-[13px] dark:border-white/[0.08] dark:bg-[#20242B]" /><textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} className="min-h-20 w-full rounded-xl border border-[#E5E7E4] bg-white p-3 text-[13px] dark:border-white/[0.08] dark:bg-[#20242B]" /><button type="button" onClick={submitEdit} className="inline-flex items-center gap-1 rounded-lg bg-[#3B82F6] px-3 py-2 text-[12px] font-semibold text-white"><Save size={14} />Save</button></div> : <><h3 className="mt-3 text-[20px] font-semibold">{details.name}</h3><p className="mt-1 text-[12px] text-[#858A92]">{details.description || "No description"}</p>{permissions.canManageRoom && <button type="button" onClick={() => { setDraft({ name: details.name, description: details.description }); setEditing(true); }} className="mt-2 text-[12px] font-medium text-[#3B82F6]">Edit room</button>}</>}<p className="mt-3 text-[10px] uppercase tracking-wide text-[#9A9EA5]">Created {new Date(details.createdAt).toLocaleDateString()} · {details.memberCount} members</p></section>
      {actionError && <p className="mt-4 rounded-xl bg-[#FBF1F1] p-3 text-[12px] text-[#A55353] dark:bg-[#3A2528] dark:text-[#E3A1A1]">{actionError}</p>}
      <section className="mt-7"><div className="mb-2 flex items-center justify-between"><h3 className="text-[13px] font-semibold">Members</h3>{permissions.canManageRoom && <button type="button" onClick={() => setShowAdd(true)} className="flex items-center gap-1 text-[11px] font-semibold text-[#3B82F6]"><Plus size={14} />Add</button>}</div><RoomMembersList members={details.members} currentUserId={currentUserId} onlineUserKeys={onlineUserKeys} permissions={permissions} onProfile={onOpenProfile} onMessage={onMessageMember} onRemove={(id) => run(() => removeMember(id))} onRoleChange={(id, role) => run(() => setRole(id, role))} /></section>
      <section className="mt-7"><h3 className="mb-3 text-[13px] font-semibold">Shared media</h3><RoomMediaGrid items={media} hasMore={mediaHasMore} onLoadMore={() => run(loadMoreMedia)} /></section>
      <section className="mt-7"><h3 className="mb-2 text-[13px] font-semibold">Room settings</h3><RoomSettingsSection muted={muted} pinned={pinned} onMute={onMute} onPin={onPin} onClear={onClear} onExit={() => setConfirmExit(true)} /></section>
    </>}</div>
    {showAdd && <AddMembersModal existingIds={memberIds} onAdd={(ids) => run(() => addMembers(ids))} onClose={() => setShowAdd(false)} />}
    {confirmExit && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/35 p-4" role="presentation"><div role="dialog" aria-modal="true" className="w-full max-w-sm rounded-[18px] bg-white p-5 dark:bg-[#20242B]"><h3 className="text-[17px] font-semibold">Exit this group?</h3><p className="mt-2 text-[12px] text-[#858A92]">You will be removed from the persisted member list. Shared history remains for other members.</p><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setConfirmExit(false)} className="rounded-xl px-4 py-2 text-[12px]">Cancel</button><button type="button" onClick={handleExit} className="rounded-xl bg-[#B65A5A] px-4 py-2 text-[12px] font-semibold text-white">Exit group</button></div></div></div>}
  </aside>;
}
